### ISSUE TITLE
King's Lynn FC is missing from teams table

### ISSUE THREAD

**Issue by fwdr** [openfootball/help#24]
Error when trying to import the database.

** !!! ERROR - no match for club >King's Lynn FC<

Looks like Kings Lynn is missing from the national league team list for 20-21

And Wealdstone who were also promoted.

**Comment by geraldb** [comment]
Sorry for the trouble - thanks for reporting the error - see the [FAQ entry in troubleshooting on how to use an up-to-date zip archive for clubs](https://github.com/openfootball/help#troubleshooting) for a DIY quick fix  otherwise sorry you have to wait for the next football-clubs library update.

**Comment by fwdr** [comment]
Thank you
