### ISSUE TITLE
Frequency of update

### ISSUE THREAD

**Issue by nurgasemetey** [openfootball/help#29]
Hello again,

It seems that `yorobot` is doing updates. I was just looking at data and it seems that last gameweek was not added. 

Do I have to make PR to https://github.com/openfootball/england or data are added automatically? :smile:

**Comment by nurgasemetey** [comment]
Thanks for reply. There is no trouble, you don't need to say sorry. You are doing enormous work. If you need collaborators, I can help you.

**Comment by geraldb** [comment]
Keep up your testing and commenting that's already a great help and of course keep up building / using the datasets and sharing your visualizations  etc. Cheers. Prost.
