### ISSUE TITLE
Request: Possibility of adding the worldcups.standings.json for World Cup 2022

### ISSUE THREAD

**Issue by CarlosQ27** [openfootball/help#38]
Hello, I'm a college student that is currently using the 2018 worldcup.json repository for a course's project. For the final phase, I was requested to use the 2022 world cup results. I noticed that you have been updating the repository for the 2022 world cup, but I need the worldcup.standings.json for my project to be able to function correctly. I don't know if there is a possibility that you could upload this JSON?

**Comment by geraldb** [comment]
I try to update the worldcup.json datasets for 2022 in the next days  - but as always no promise / guarantee. 

PS:  The best way is to do-it-yourself (DIY) - yes, you can - try to export the JSON datasets yourself from the sport.db / worldcup.db (single-file local SQLite database) using your scripting / statistics language of choice.
