### ISSUE TITLE
Different format for scores

### ISSUE THREAD

**Issue by pel-daniel** [openfootball/help#43]
👋🏽 Thanks for the project!
I noticed that the format of scores for the year 2020 is different than for 2024.
What's a good way to contribute a PR to fix it, as I see that these files are probably auto-generated from the https://github.com/openfootball/euro repo

**Comment by geraldb** [comment]
welcome to football.db.    good catch.  yes, the format is changing.   i  updated the euro 2020 (2021) json datafiles to the new (score) format. yes, the json files are auto-generated. see here for the quick & dirty script - <https://github.com/yorobot/sport.db.more/blob/master/sportdb-exporters/lib/sportdb/exporters/json_exporter_euro.rb>

**Comment by pel-daniel** [comment]
Thanks for the fix!
